version: "3.9"
services:
  app:
    build:
      context: ./app
    env_file:
      - .env
    ports:
      - "${FLASK_PORT:-5002}:5002"
    depends_on:
      - db
    networks:
      - app-net
    # Em produção, não monte o volume do código
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-net
volumes:
  db-data:
networks:
  app-net:
    driver: bridge